/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC			0x40023800
#define GPIOD		0x40020C00

#define RCC_AHB1ENR		(RCC + 0x30)
#define GPIOD_MODER		(GPIOD + 0x00)
#define GPIOD_ODR		(GPIOD + 0x14)

long long gDelay = 100000;

void delay()
{
	for ( uint32_t i=0; i<gDelay; i++ )
	{
		// empty loop - do nothing
	}
}

void setInitialState( uintptr_t * const pGPIO_OutputDataDReg )
{
	// "clear" LEDs
	*pGPIO_OutputDataDReg &= ~( 0x0 << 12 );

	printf("\t- LEDs Initial\n");
	*pGPIO_OutputDataDReg |= ( 0xA << 12 );

}

void toggle( uintptr_t* const pGPIO_OutputDataDReg )
{
	printf("\t- LEDs Toggle\n");
	*pGPIO_OutputDataDReg ^= ( 0xF << 12 );

	return;
}

int main(void)
{
	uintptr_t* pRCC_AHB1EnrReg = (uintptr_t*) RCC_AHB1ENR;
	uintptr_t* pGPIOD_ModeReg = (uintptr_t*) GPIOD_MODER;
	uintptr_t* pGPIOD_OutputDataDReg	= (uintptr_t*) GPIOD_ODR;

	// enable the peripheral D clock
	*pRCC_AHB1EnrReg |= ( 1 << 3 );

	// set the mode - MODER15-MODER12 (LED3-LED6) Output (01)
	*pGPIOD_ModeReg &= ~( 0xFF << 24 );
	*pGPIOD_ModeReg |=  ( 0x55 << 24 );

	setInitialState( pGPIOD_OutputDataDReg );

	/* Loop forever */
	while( 1 )
	{
		delay();

		toggle( pGPIOD_OutputDataDReg );
	}

}
