/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define EXTI 		0x40013C00
#define EXTI_IMR 	( EXTI + 0x00 )
#define EXTI_RTSR 	( EXTI + 0x08 )
#define EXTI_PR		( EXTI + 0x14 )

#define RCC			0x40023800
#define RCC_AHB1ENR	( RCC + 0x30 )
#define RCC_APB2ENR	( RCC + 0x44 )

#define GPIOA		0x40020000
#define GPIOA_MODER	( GPIOA + 0x00 )



uint8_t gButtonPressed = 0;
uint32_t gButtonPressedCount = 0;

void buttonInit();

uintptr_t volatile *pRCC_AHB1EnrReg = (uintptr_t*) RCC_AHB1ENR;

uintptr_t *pEXTI_IMR


int main(void)
{
    /* Loop forever */
	for(;;);
}
