/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC			0x40023800
#define GPIOA    	0x40020000
#define GPIOD		0x40020C00

#define RCC_AHB1ENR		(RCC + 0x30)

#define GPIOA_MODER		(GPIOA + 0x00)
#define GPIOA_IDR		(GPIOA + 0x10)

#define GPIOD_MODER		(GPIOD + 0x00)
#define GPIOD_ODR		(GPIOD + 0x14)

long long gDelay = 100000;

void splash()
{
	printf( "*****************\n" );
	printf( "*  006_PinRead  *\n" );
	printf( "*****************\n" );

	return;
}

void delay()
{
	for ( uint32_t i=0; i<gDelay; i++ )
	{
		// empty loop - do nothing
	}

	return;
}

void setInitialState( uintptr_t * const pGPIO_OutputDataDReg )
{
	// "clear" LEDs
	*pGPIO_OutputDataDReg &= ~( 0x0 << 12 );

	// turn on two of them
	*pGPIO_OutputDataDReg |= ( 0xA << 12 );

	return;
}

void toggle( uintptr_t* const pGPIO_OutputDataDReg )
{
	*pGPIO_OutputDataDReg ^= ( 0xF << 12 );

	return;
}

int main(void)
{
	splash();

	uintptr_t* pRCC_AHB1EnrReg = (uintptr_t*) RCC_AHB1ENR;

	uintptr_t* pGPIOA_ModeReg = 		(uintptr_t*) GPIOA_MODER;
	uintptr_t* pGPIOA_InputDataReg = 	(uintptr_t*) GPIOA_IDR;

	uintptr_t* pGPIOD_ModeReg = 		(uintptr_t*) GPIOD_MODER;
	uintptr_t* pGPIOD_OutputDataDReg =	(uintptr_t*) GPIOD_ODR;


	// enable the peripheral clock for GPIO A & D
	*pRCC_AHB1EnrReg |= ( 1 << 0 );
	*pRCC_AHB1EnrReg |= ( 1 << 3 );

	// GPIOA : MODE01[1:0] : PA0/B1 USER Input
	*pGPIOA_ModeReg &= ~( 0x3 << 0 );

	// GPIOD : MODER15[1:0] - MODER12[1:0] : (LED3-LED6) Output (01)
	*pGPIOD_ModeReg &= ~( 0xFF << 24 );
	*pGPIOD_ModeReg |=  ( 0x55 << 24 );

	setInitialState( pGPIOD_OutputDataDReg );

	/* Loop forever */
	while( 1 )
	{
		int8_t value = *pGPIOA_InputDataReg & 1;

		if ( value == 1 )
		{
			gDelay = 50000;
		}
		else
		{
			gDelay = 100000;
		}

		delay();

		toggle( pGPIOD_OutputDataDReg );
	}

}
