/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC			0x40023800
#define GPIOA    	0x40020000
#define GPIOD		0x40020C00

#define RCC_AHB1ENR		(RCC + 0x30)

#define GPIOA_MODER		(GPIOA + 0x00)
#define GPIOA_IDR		(GPIOA + 0x10)

#define GPIOD_MODER		(GPIOD + 0x00)
#define GPIOD_ODR		(GPIOD + 0x14)

enum LedState
{
	NONE = 0x00,
	GREEN = 0x01,
	ORANGE = 0x02,
	RED = 0x04,
	BLUE = 0x08,
	ALL = RED | GREEN | BLUE | ORANGE
};
typedef enum LedState Color;

enum Spin
{
	CLOCKWISE,
	COUNTER
};
typedef enum Spin Direction;

enum Function
{
	CLEAR,
	LIGHT,
	TOGGLE,
	SPINCLOCKWISE,
	SPINCOUNTER,
	FLASH,
	UNKNOWN
};
typedef enum Function Mode;


void splash()
{
	printf( "*****************\n" );
	printf( "*  006_PinRead  *\n" );
	printf( "*****************\n" );

	return;
}

void delay( uint64_t cycles )
{
	for ( uint32_t i=0; i<cycles; i++ )
	{
		// empty loop - do nothing
	}

	return;
}

void setLEDs( uintptr_t volatile *const pGPIO_OutputDataDReg, Color color )
{
	// clear then set to color
	*pGPIO_OutputDataDReg &= ~( 0xF << 12 );
	*pGPIO_OutputDataDReg |= ( color << 12 );

	return;
}

void clear( uintptr_t volatile *const pGPIO_OutputDataDReg )
{
	setLEDs( pGPIO_OutputDataDReg, NONE );

	return;
}

void light( uintptr_t volatile *const pGPIO_OutputDataDReg )
{
	setLEDs( pGPIO_OutputDataDReg, ALL );

	return;
}

void toggle( uintptr_t volatile *const pGPIO_OutputDataDReg )
{
	*pGPIO_OutputDataDReg ^= ( 0xF << 12 );

	return;
}

void spin( uintptr_t volatile *const pGPIO_OutputDataDReg, Direction spin )
{
	uint16_t value = (*pGPIO_OutputDataDReg & (0xF << 12)) >> 12;

	if ( spin == CLOCKWISE )
	{
		value = (value << 1);
		if ( value & 0x10 )
			value = 1;
		else
			value &= 0xF;
	}
	else
	{
		uint8_t carry = 0;
		if ( value & 0x01 )
			carry = 1;

		value >>= 1;
		value |= (carry << 3 );
	}

	*pGPIO_OutputDataDReg &= ~( 0xF << 12 );
	*pGPIO_OutputDataDReg |= ( value << 12 );

	return;
}

void flash( uintptr_t volatile *const pGPIO_OutputDataDReg )
{
	static bool ledsOn = true;

	if ( ledsOn )
	{
		clear( pGPIO_OutputDataDReg );
		ledsOn = false;
	}
	else
	{
		light( pGPIO_OutputDataDReg );
		ledsOn = true;
	}

	return;
}

int main(void)
{
	const uint64_t delayChangeMode = 5;

	Mode mode = UNKNOWN;
	Mode nextMode = LIGHT;

	uint64_t changeModeCount = 0;
	uint64_t delayCycles = 100000;

	uintptr_t volatile *const pRCC_AHB1EnrReg = (uintptr_t*) RCC_AHB1ENR;

	uintptr_t volatile *const pGPIOA_ModeReg = 		(uintptr_t*) GPIOA_MODER;
	uintptr_t volatile *const pGPIOD_ModeReg = 		(uintptr_t*) GPIOD_MODER;

	uintptr_t volatile *const pGPIOA_InputDataReg = 	(uintptr_t*) GPIOA_IDR;
	uintptr_t volatile *const pGPIOD_OutputDataDReg =		(uintptr_t*) GPIOD_ODR;

	splash();

	// enable the peripheral clock for GPIO A & D
	*pRCC_AHB1EnrReg |= ( 1 << 0 );
	*pRCC_AHB1EnrReg |= ( 1 << 3 );

	// GPIOA : MODE01[1:0] : PA0/B1 USER Input
	*pGPIOA_ModeReg &= ~( 0x3 << 0 );

	// GPIOD : MODER15[1:0] - MODER12[1:0] : (LED3-LED6) Output (01)
	*pGPIOD_ModeReg &= ~( 0xFF << 24 );
	*pGPIOD_ModeReg |=  ( 0x55 << 24 );

	setLEDs( pGPIOD_OutputDataDReg, GREEN );

	/* Loop forever */
	while( 1 )
	{
		int8_t value = *pGPIOA_InputDataReg & 1;

		if ( value == 0 )
		{
			changeModeCount = 0;

			if ( mode != nextMode )
			{
				mode = nextMode;

				// set initial states
				switch (mode)
				{
				case CLEAR:
					// nothing
					break;
				case LIGHT:
					// nothing
					break;
				case TOGGLE:
					setLEDs( pGPIOD_OutputDataDReg, RED | GREEN );
					break;
				case SPINCLOCKWISE:
				case SPINCOUNTER:
					setLEDs( pGPIOD_OutputDataDReg, GREEN );
					break;
				case FLASH:
					clear( pGPIOD_OutputDataDReg );
					break;
				default:
					break;
				}
			}
		}
		else
		{
			changeModeCount++;
		}

		if ( changeModeCount > delayChangeMode )
		{
			setLEDs( pGPIOD_OutputDataDReg, NONE );

			// crazy simple state machine
			switch (mode )
			{
			case CLEAR:
				nextMode = LIGHT;
				break;
			case LIGHT:
				nextMode = TOGGLE;
				break;
			case TOGGLE:
				nextMode = SPINCLOCKWISE;
				break;
			case SPINCLOCKWISE:
				nextMode = FLASH;
				break;
			case FLASH:
				nextMode = SPINCOUNTER;
				break;
			case SPINCOUNTER:
				nextMode = LIGHT;
				break;
			default:
				nextMode = CLEAR;
				break;
			}
		}
		else
		{
			switch (mode )
			{
			case CLEAR:
				clear( pGPIOD_OutputDataDReg );
				break;
			case LIGHT:
				light( pGPIOD_OutputDataDReg );
				break;
			case TOGGLE:
				toggle( pGPIOD_OutputDataDReg );
				break;
			case SPINCLOCKWISE:
				spin(pGPIOD_OutputDataDReg, CLOCKWISE );
				break;
			case SPINCOUNTER:
				spin(pGPIOD_OutputDataDReg, COUNTER );
				break;
			case FLASH:
				flash( pGPIOD_OutputDataDReg );
				break;
			default:
				clear( pGPIOD_OutputDataDReg );
				break;
			}
		}

		delay( delayCycles );
	}


}
