/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>

#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC			0x40023800
#define RCC_AHB1ENR	(RCC + 0x30)

#define GPIOA    	0x40020000
#define GPIOA_MODER	(GPIOA + 0x00)
#define GPIOA_IDR	(GPIOA + 0x10)

#define GPIOD		0x40020C00
#define GPIOD_MODER	(GPIOD + 0x00)
#define GPIOD_ODR	(GPIOD + 0x14)

void splash()
{
	printf( "******************************\n" );
	printf( "*  010_LED Toggle Bit Fields *\n" );
	printf( "******************************\n" );
	printf("\n");

	return;
}

void delay( uint64_t cycles )
{
	for ( uint32_t volatile i=0; i<cycles; i++ )
	{
		// empty loop - do nothing
	}

	return;
}

int main(void)
{
	uint64_t delayCycles = 100000;

	RCC_AHB1ENR_t volatile *const pRCC_AHB1EnrReg = 	(RCC_AHB1ENR_t*) RCC_AHB1ENR;

	GPIOx_MODER_t volatile *const pGPIOA_ModeReg = 		(GPIOx_MODER_t*) GPIOA_MODER;
	GPIOx_IDR_t volatile *const pGPIOA_InputDataReg = 	(GPIOx_IDR_t*) GPIOA_IDR;

	GPIOx_MODER_t volatile *const pGPIOD_ModeReg = 		(GPIOx_MODER_t*) GPIOD_MODER;
	GPIOx_ODR_t volatile *const pGPIOD_OutputDataDReg =	(GPIOx_ODR_t*) GPIOD_ODR;

	splash();

	pRCC_AHB1EnrReg->gpioa_en = 1;
	pRCC_AHB1EnrReg->gpiod_en = 1;

	pGPIOA_ModeReg->mode_r0  = 0x00;
	pGPIOD_ModeReg->mode_r12 = 0x01;
	pGPIOD_ModeReg->mode_r13 = 0x01;
	pGPIOD_ModeReg->mode_r14 = 0x01;
	pGPIOD_ModeReg->mode_r15 = 0x01;

	// set initial values for LEDs
	pGPIOD_OutputDataDReg->od_r12 = 1;
	pGPIOD_OutputDataDReg->od_r13 = 1;
	pGPIOD_OutputDataDReg->od_r14 = 1;
	pGPIOD_OutputDataDReg->od_r15 = 1;

    /* Loop forever */
	while (1)
	{
		delay( delayCycles );

		pGPIOD_OutputDataDReg->od_r12 ^= 1;
		pGPIOD_OutputDataDReg->od_r13 ^= 1;
		pGPIOD_OutputDataDReg->od_r14 ^= 1;
		pGPIOD_OutputDataDReg->od_r15 ^= 1;

		uint8_t pressed = pGPIOA_InputDataReg->id_r0;

		if ( pressed )
		{
			delayCycles = 50000;
		}
		else
		{
			delayCycles = 100000;
		}

	}
}
